name: horta_app
description: App de Monitoramento da Horta Inteligente.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # MQTT
  mqtt_client: ^10.0.0

  # Gráficos de Velocímetro (Dashboard)
  syncfusion_flutter_gauges: ^25.0.0

  # Gráficos de Linha (Histórico)
  fl_chart: ^0.68.0

  # Notificações do Celular (Versão corrigida do bug de compilação)
  flutter_local_notifications: ^17.0.0

  # Formatação de Data
  intl: ^0.19.0

  # Ícones
  cupertino_icons: ^1.0.2
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
